### ISSUE TITLE
Compile failes with latest code from master

### ISSUE THREAD

**Issue by rbri** [assertthat/selenium-shutterbug#101]
Many thanks for this great tool.
Did some tests with strange web sites and for most of them it did a great job. But i had to digg deeper because the snapshot was not correct for some pages (sorry but the pages are not public so far).

So i start to do some debugging. But after the initial checkout i got a compile error with the head revision - some (simple) methods where missing for class ImageData (getImage(), getWidth(), getHeight()).

Have a done something wrong?

**Comment by glib-briia** [comment]
Hi @rbri 

Thank you for your feedback. The reason you are seeing compilation errors is that the project uses Lombock for automatically generating getters, constructors etc. If you are using IntelliJ IDEA you can install this plugin which will make those errors go away https://plugins.jetbrains.com/plugin/6317-lombok 

The project compiles fine thought using maven e.g. mvn clean compile

**Comment by rbri** [comment]
Ah ok i see. I'm using eclipse and i have used maven only to setup the eclipse project. And then the compile in eclipse failed. 
In general i think having less dependencies is always a good idea maybe simply adding 3 getter methods is not that hard.
Thanks for your fast response and a great tool, feel free to close this.
   Ronald

**Comment by glib-briia** [comment]
Yes, that's true, the initial thought was that it'll be used a lot more, I've got it removed now. Thank you for pointing out

**Comment by rbri** [comment]
Thanks
