### ISSUE TITLE
Scrollbars are visible in Chrome 54, and only the first "row" is collected

### ISSUE THREAD

**Issue by ChristophKaser** [assertthat/selenium-shutterbug#14]
Steps to reproduce:

- Open the following url using selenium with chrome 54:
`data:text/html;charset=utf-8;base64,PGh0bWw+DQoJPGJvZHkgc3R5bGU9ImhlaWdodDogMzcyOXB4OyB3aWR0aDogMTQ2NXB4OyBtYXJnaW46IDBweDsgcGFkZGluZzogMHB4OyBiYWNrZ3JvdW5kLWltYWdlOiBsaW5lYXItZ3JhZGllbnQodG8gbGVmdCB0b3AsIGJsdWUsIHJlZCk7IGJhY2tncm91bmQtc2l6ZTogMTQ2NXB4IDEwMCU7Ij4NCgk8L2JvZHk+DQo8L2h0bWw+`
- Take a screenshot
`Shutterbug.shootPage(driver, ScrollStrategy.BOTH_DIRECTIONS).getImage()`

**expected:**
<img src="https://cloud.githubusercontent.com/assets/8121794/19961466/1610d6e8-a1b3-11e6-9514-3f2befca51c9.png" alt="expected" width="100">
**received:**
<img src="https://cloud.githubusercontent.com/assets/8121794/19961694/3c9ce440-a1b4-11e6-8287-e60f1793b2e9.png" alt="received" width="100">

There are actually two problems:
- The scrollbars are visible
- The viewport height is wrong, and therefore only the first line is queried

I will submit a PR that fixes these problems

**Comment by glib-briia** [comment]
Fixed by https://github.com/assertthat/selenium-shutterbug/pull/15
