### ISSUE TITLE
selenium-shutterbug -0.4 unable to see equalsWithDiff functions

### ISSUE THREAD

**Issue by regisrozario** [assertthat/selenium-shutterbug#19]
Hi,

I added the following dependencies to my project
<dependency>
    <groupId>com.assertthat</groupId>
    <artifactId>selenium-shutterbug</artifactId>
    <version>0.4</version>
</dependency>

But am unable to access the following funtion "Shutterbug.shootPage(driver).equalsWithDiff(otherImage,pathToNewImage,0.1);"

I could see only .equals methods.

**Comment by glib-briia** [comment]
Hi @regisrozario ,

This feature is available since v 0.5.

Please update your dependency:
https://search.maven.org/#artifactdetails%7Ccom.assertthat%7Cselenium-shutterbug%7C0.5%7Cjar

Thanks,
Glib
