### ISSUE TITLE
Save function should either take a parameter for filename or return the file/file path

### ISSUE THREAD

**Issue by pigucatalin** [assertthat/selenium-shutterbug#2]
Save function should either take a parameter for filename or return the file/file path in case it's needed to log in error messages, compare with other failures ..

**Comment by glib-briia** [comment]
Hi @pigucatalin,

You can use withName("screenshot name here") method to set screenshot name and there is overloaded save method which takes the path to save to as a parameter save(String path)

Please let me know if this is sufficient enough.

Thanks,
Glib

**Comment by pigucatalin** [comment]
Thank you
