### ISSUE TITLE
Retina methods are not available

### ISSUE THREAD

**Issue by nikprix** [assertthat/selenium-shutterbug#20]
I added newest available version of shutterbug to my POM:

`        <dependency>` 
          `   <groupId>com.assertthat</groupId> ` 
           `  <artifactId>selenium-shutterbug</artifactId>` 
           `  <version>0.5</version>` 
`  </dependency>` 

but newest retina methods are not loading:
Sources:

```
public class Shutterbug {

    private static final int DEFAULT_SCROLL_TIMEOUT = 100;

    public Shutterbug() {
...
    }

    public static PageSnapshot shootPage(WebDriver driver) {
...
    }

    public static PageSnapshot shootPage(WebDriver driver, ScrollStrategy scroll) {
...
    }

    public static PageSnapshot shootPage(WebDriver driver, ScrollStrategy scroll, int scrollTimeout) {
...
    }

    public static ElementSnapshot shootElement(WebDriver driver, WebElement element) {
...
    }
}
```

Am I doing something wrong?

**Comment by glib-briia** [comment]
Hi @nikprix ,

Thank you for reporting this. The issue occurred due to the error during 0.5 release.

Fixed in 0.6
Please update your dependency.
