### ISSUE TITLE
Vertical Screenshot on Mobile is HALVED

### ISSUE THREAD

**Issue by jglifonea** [assertthat/selenium-shutterbug#22]
Tried the code below :

Shutterbug.shootPage(driver, ScrollStrategy.VERTICALLY).save("/screenshots");

Result is that the VERTICAL part is captured correctly, but the HORIZONTAL part is missing.

Tried removing the ScrollStrategy and it works fine but I'm missing the whole page screenshot.

**Comment by glib-briia** [comment]
Hi jglifonea,
Try using the following to make full page screenshot: Shutterbug.shootPage(driver, ScrollStrategy.BOTH_DIRECTIONS).save("/screenshots");

More examples here: https://github.com/assertthat/selenium-shutterbug/wiki/Examples-of-usage

**Comment by jglifonea** [comment]
Hi @glib-briia,
I also tried using BOTH_DIRECTIONS but it was the same as VERTICAL.
I tested this on an android device running on Appium.
In chrome WEB (Laptop), it works fine though. 

Also, may I know the latest version of shutterbug?

**Comment by jglifonea** [comment]
Attaching actual screenshot. Tested on google website.

http://pasteboard.co/8ngfXTM8M.png

**Comment by glib-briia** [comment]
Hi @jglifonea ,

Since you are running on devices, you might need to account for devisePixelRatio. Could you please try the following:
  Shutterbug.shootPage(driver, ScrollStrategy.BOTH_DIRECTIONS,500,true).save("/screenshots");

The argument 'true' indicates that Shutterbug will use devicePixelRatio.

**Comment by glib-briia** [comment]
The latest version is 0.6

**Comment by jglifonea** [comment]
@glib-briia oh yes it works! Ive been looking for days for this and I also use shutterbug now for both WEB and Mobile for screenshots! Used version 0.6. Thanks for this!
