### ISSUE TITLE
ShutterBug is not taking proper screenshots in Chrome 58

### ISSUE THREAD

**Issue by PavaniSamineni** [assertthat/selenium-shutterbug#23]
Hi,

Am able to take full web page screenshots in Chrome 57, but Chrome got updated to 58 and from then we are not able to take proper screenshot.

Please fine the screenshot before and after the update of chrome.

[ShutterBug Issue_Chrome58.docx](https://github.com/assertthat/selenium-shutterbug/files/970564/ShutterBug.Issue_Chrome58.docx)

**Comment by glib-briia** [comment]
Hi @PavaniSamineni ,

Could you please provide the sample code you are running while taking screenshot and you environment details (e.g. OS version, screen resolution, chromedriver version).

**Comment by glib-briia** [comment]
HI @PavaniSamineni ,

You might need to use the following in order to account for devicePixelRatio:
````
Shutterbug.shootPage(driver, ScrollStrategy.BOTH_DIRECTIONS,500,true).save();

**Comment by PavaniSamineni** [comment]
Hi Glib-Briia,
 
I have tried suggested line but am facing below error, am trying to figure out where am getting it and this error I can see only for chrome 58 not for 57.
"java.lang.Double cannot be cast to java.lang.Long"

This the piece of code am using 
"
File screenshotFile = new File("saved.png");
		
		BufferedImage screenshotBuffered = null;
		//screenshotBuffered=Shutterbug.shootPage(webDriver, ScrollStrategy.BOTH_DIRECTIONS).getImage();
		screenshotBuffered=Shutterbug.shootPage(webDriver, ScrollStrategy.BOTH_DIRECTIONS,500,true).getImage();
		ImageIO.write(screenshotBuffered, "png",screenshotFile);
"

and below are the details that you have asked for

OS : Windows 7
Screen Resolution : 1920 X 1080
Device Pixel Ratio : No idea on Where to get or how to check for DevicePixelRatio
Chrome driver Version : 2.28

**Comment by PavaniSamineni** [comment]
Hi Glib-Briia,

To be clear specifications for the system which has chrome 57 are 

OS : Windows 7
Screen Resolution : 1600 X 900
Device Pixel Ratio : No idea on Where to get or how to check for DevicePixelRatio
Chrome driver Version : 2.28

And for system having chrome 58

OS : Windows 7
Screen Resolution : 1920 X 1080
Device Pixel Ratio : No idea on Where to get or how to check for DevicePixelRatio
Chrome driver Version : 2.28

**Comment by glib-briia** [comment]
Hi @PavaniSamineni ,

The exception you are getting is caused the change introduced in Chrome 58 and is not handled it shutterbug yet. Basically, devicePixelRatio is now can be not only integer/long but double as well.
Fixed now in @0cf027fd2658324766e4f164d3c64988f48ddebf and will appear in new version on shutterbug.

**Comment by glib-briia** [comment]
Version 0.6.1 is now released.

**Comment by glib-briia** [comment]
Also you'd better update Chromedriver to the latest v 2.29

**Comment by PavaniSamineni** [comment]
Hi glib-briia,

Thank you, its working now in chrome 58.
And one more thing would like to know is there any version limitation for using it in firefox.

bcz with the version 40 am getting this "this.getChromeWindowFromDocumentWindow(...) is undefined" 
and for 38 its executing properly.

**Comment by glib-briia** [comment]
Hi @PavaniSamineni ,

There are no limitations for using Shutterbug in FF.
The error you are getting is not Shutterbug specific, its rather you configuration specific. 
More datails on this error can be found here http://stackoverflow.com/questions/35029386/getting-org-openqa-selenium-webdriverexception-this-getchromewindowfromdocument
