### ISSUE TITLE
Headers and other Static Web contents issue

### ISSUE THREAD

**Issue by jglifonea** [assertthat/selenium-shutterbug#25]
So I'm currently using the code below :

Shutterbug.shootPage(driver, ScrollStrategy.BOTH_DIRECTIONS, 300).withName(fileName).save(screenshotDestination.getAbsolutePath());

It successfully makes the screenshot but the headers and fixed images are always stuck on the screenshot.png file. 

Please see images on the links : 
The header is always on the screenshot : https://drive.google.com/file/d/0B_PXSe2aM-mTc1dYdjlIelhrX00/view?usp=sharing

Are there any workaround on this issue?

**Comment by GiGaByTee** [comment]
Hello
You can make the header static before taking  a screenshot

**Comment by jglifonea** [comment]
@GiGaByTee what do you mean by "Make the header static"?

**Comment by GiGaByTee** [comment]
@jglifonea , u can run js script which will make your header static. 
In your case, header has attribute 'fixed', so its always at the top of the page while scrolling

**Comment by jglifonea** [comment]
@GiGaByTee I tried checking on your advice, thank you.
Before the capture of screenshot, the JS code should be executed to make the header fixed. 
Since we are using ShutterBug, it automatically captures the whole page including the scrolling-down of the page itself.
Personally, I don't have in-depth knowledge of JavaScript. Can you specify an example on this or code snippet?

**Comment by GiGaByTee** [comment]
@jglifonea , Yes, you are right about ShutterBug flow.
For example - there is such an element in DOM
<header id='fixed-header' style='position:fixed'></header>
or style attribute may not be directly written in element, but through  css, in your case.
So, u need something like this to make your header static:
`document.getElementById("fixed-header").style.position='static'`
or, if you use selenium+java:
`WebElement wb = webDriver.findElement(By.id("fixed-header"));
((JavascriptExecutor) webDriver).executeScript("arguments[0].style.position='static'", wb);
`
Hope it will help you.

**Comment by jglifonea** [comment]
@GiGaByTee the code did not work but I changed the static to relative and it worked.

((JavascriptExecutor)webDriver).executeScript("arguments[0].style.position='relative'", wb);

Thank you very much for the help!

**Comment by GiGaByTee** [comment]
@jglifonea, nice)
In case of any questions u could contact me via skype - lesnazarko1
