### ISSUE TITLE
Usage with FitNesse/Selenium stack

### ISSUE THREAD

**Issue by roboaks** [assertthat/selenium-shutterbug#27]
Has anyone got selenium-shutterbug to work with FitNesse running on top of Selenium? We're a Java shop but, in the FitNesse/Selenium context, it isn't clear how to get this working. We can run arbitrary Javascript within the SUT (system under test) in the browser, but I'm not sure that helps.

Thanks for your help.

**Comment by glib-briia** [comment]
Discussion moved here https://www.assertthat.com/posts/selenium_shutterbug_make_custom_screenshots_with_selenium_webdriver

Closing.
