### ISSUE TITLE
[help] Infinite scrolling pages - timeout?

### ISSUE THREAD

**Issue by ivanviragine** [assertthat/selenium-shutterbug#28]
Hi!

What's the best approach on screenshots for infinite scrolling page?
Is there a maximum scrolling time parameter or something like this?
From what I've saw in the source code, there isn't such a param... anyway, would this be the best approach?

**Comment by glib-briia** [comment]
Hi @ivanviragine ,
Thank you for your question. Actually, for your scenario with 'infinite' scrolling page shutterbug wont scroll indefinitely, it will capture only the part of the page that was initially loaded e.g. first batch and wont scroll down for dynamically loaded content. Have you tried using it with such a page?
Thanks,
Glib

**Comment by ivanviragine** [comment]
@glib-briia I'll try again, but, I was testing on a Facebook Page page, and it timed-out because of infinite scrolling. I'll check again and get back to you, ok?

**Comment by glib-briia** [comment]
Hi @ivanviragine , any update on this one?

**Comment by ivanviragine** [comment]
Sorry about the delay @glib-briia !
Several other pages are working! I think there was something else in my code that was scrolling...

I'll try again later!

**Comment by glib-briia** [comment]
Thank you for your reply @ivanviragine . Closing for now. Feel free to reopen if it is still an issue.
