### ISSUE TITLE
Crop page and focus on captured element

### ISSUE THREAD

**Issue by gavrilfb** [assertthat/selenium-shutterbug#32]
Currently if we use the _.shootElement_ it will result in only the defined element captured.
![2017_10_04_13_54_40_749](https://user-images.githubusercontent.com/29943195/31163276-ebacf236-a90b-11e7-88db-526fab426518.png)

Is it possible to setup so we can capture the element while still showing relative other elements around?
![2017_10_04_13_54_40_298](https://user-images.githubusercontent.com/29943195/31163336-231cbabc-a90c-11e7-8c47-f405344733cc.png)

**Comment by glib-briia** [comment]
Hi @gavrilfb ,

You mean blur the page except needed element?

**Comment by gavrilfb** [comment]
@glib-briia Yes, but it would be nice if we can capture not the whole page, but the needed element with several elements around it. So the image size not bloated.

**Comment by glib-briia** [comment]
Hi @gavrilfb ,

You'll be able to do that in 0.7 version. Example below:

```
driver.get("http://google.com/");
WebElement googleLogo = driver.findElement(By.id("hplogo"));
Shutterbug.shootPage(driver, ScrollStrategy.VERTICALLY).blurExcept(googleLogo).cropAround(googleLogo,150,160)
```
![2017_10_04_12_10_07_209](https://user-images.githubusercontent.com/16775850/31176380-98bd114c-a90a-11e7-9643-97c971501dbf.png)
