### ISSUE TITLE
Not finiding Element corretly

### ISSUE THREAD

**Issue by Aathimanirajb** [assertthat/selenium-shutterbug#36]
Hi Team,
This is working fine but it is not finding element correctly help me out to proceed further
Not finding Element correctly

![f-1512823962763](https://user-images.githubusercontent.com/34085411/33796452-86e9a630-dd1a-11e7-88b1-8204e06e9053.png)
![f-1512823960268](https://user-images.githubusercontent.com/34085411/33796453-873018c2-dd1a-11e7-8a56-3e75b511cc4c.png)

**Comment by glib-briia** [comment]
Hi, could you add more details e.g. screenshot, code sample etc.

**Comment by glib-briia** [comment]
No feedback. Closing
