### ISSUE TITLE
ScrollStrategy halves screenshots

### ISSUE THREAD

**Issue by OliverJohnsonWork** [assertthat/selenium-shutterbug#37]
While using ScrollStrategy to capture full page screenshot, it halves output screenshots (for some reason).
Code example:
```
        WebDriver driver = new ChromeDriver();
        driver.get("https://www.linkedin.com");
        Shutterbug.shootPage(driver).save(".");
        Shutterbug.shootPage(driver, ScrollStrategy.VERTICALLY).save(".");
```

Resultant screenshots:
![2017_12_27_16_05_58_785](https://user-images.githubusercontent.com/24840512/34383766-52bbf9da-eb20-11e7-887a-7eda515353ea.png)
![2017_12_27_16_06_00_650](https://user-images.githubusercontent.com/24840512/34383767-52d99440-eb20-11e7-84e8-860456da93be.png)

**Comment by glib-briia** [comment]
Hi @OliverJohnsonWork ,

have you tried using the following:
```
Shutterbug.shootPage(driver, ScrollStrategy.BOTH_DIRECTIONS,500,true).save();
```
true in the arguments list stand for devicePixelRatio on HiDPI or Retina displays.
Thanks,
Glib

**Comment by OliverJohnsonWork** [comment]
@glib-briia It fixed my issue. Thank you.
