### ISSUE TITLE
Get rid of deprecated scroll - and - stitch. Use chrome commands and default screenshotting for other browsers 

### ISSUE THREAD

**Issue by glib-briia** [assertthat/selenium-shutterbug#42]

**Comment by glib-briia** [comment]
Needs to be done togather with #43

**Comment by galkina-anna** [comment]
Hi @glib-briia !

Wasn't it implemented in scope of #41  ? 
Using ScrollStrategy.WHOLE_PAGE we take screenshot for Chrome by means of Chrome commands, and for others - default scrolling+screenshoting implementation.

Thank you,
Anna

**Comment by glib-briia** [comment]
Hi @galkina-anna, you right, it was. Can be closed now
