### ISSUE TITLE
Gaps in full-page screenshots and cut off on the right side (IE 8)

### ISSUE THREAD

**Issue by Vitalthorbi** [assertthat/selenium-shutterbug#61]
(Edit: I meant IE 11)

Hi, 

I'm running into this issue where there are gaps in my full-page screenshots and a cut-off down the middle on the right side. 

![2019_10_02_09_27_55_676](https://user-images.githubusercontent.com/52708142/66053057-43f9a500-e4f7-11e9-9dee-19127fcadf92.png)

Here's a snippet of the relevant code:

`
        WebDriver ieDriver = new InternetExplorerDriver();
        DesiredCapabilities capabilities = DesiredCapabilities.internetExplorer();
     capabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, true); //disable protected mode settings
        capabilities.setCapability("ignoreProtectedModeSettings", true);
        capabilities.setCapability("initialBrowserUrl", "https://stackoverflow.com/");
        ieDriver = new InternetExplorerDriver(capabilities);
        Shutterbug.shootPage(ieDriver, ScrollStrategy.BOTH_DIRECTIONS,500,true).save(saveToDirectory);
`
Can anyone see something wrong or have any ideas on a fix for this?

Thanks in advance!

**Comment by Vitalthorbi** [comment]
I'm using Shutterbug 0.9.3, Selenium 3.141.59, InternetExplorerDriver 32 bits, Java 8.

**Comment by glib-briia** [comment]
Hi @Vitalthorbi ,

Is no longer available in v0.9.3, so I'm wondering how you managed to use it? are you definitely using 0.9.3?

Try changing to Shutterbug.shootPage(ieDriver, ScrollStrategy.WHOLE_PAGE,500,true).save(saveToDirectory);

**Comment by Vitalthorbi** [comment]
Hi @glib-briia , thanks for replying.

I'm using Maven and running 0.9.3. This is the dependency in my POM:

```
<!-- https://mvnrepository.com/artifact/com.assertthat/selenium-shutterbug -->
<dependency>
    <groupId>com.assertthat</groupId>
    <artifactId>selenium-shutterbug</artifactId>
    <version>0.9.3</version>
</dependency>
```
Trying your suggestion didn't fix the issue - the right side is still cutoff and there are gaps still. 

![2019_10_03_08_50_31_304](https://user-images.githubusercontent.com/52708142/66132718-1c6c1080-e5bb-11e9-89f1-9218a88b9266.png)

Do you have any other suggestions? Should I try a different version?

**Comment by Vitalthorbi** [comment]
Doing a Viewport only shot still has the cutoff on the right side. I'm suspecting that it's a device ratio issue? Shutterbug seems to have a preferred dimension where it only takes the screenshot. 

`Shutterbug.shootPage(ieDriver, ScrollStrategy.VIEWPORT_ONLY,5000,true).save(saveToDirectory);`

![2019_10_03_09_23_59_680](https://user-images.githubusercontent.com/52708142/66135542-bb930700-e5bf-11e9-9786-a92b1ac3f5bf.png)

**Comment by glib-briia** [comment]
Which IE driver version are you using? 

Just tried with your code

```
        WebDriver ieDriver;
        DesiredCapabilities capabilities = DesiredCapabilities.internetExplorer();
        capabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, true);
        //disable protected mode settings
        capabilities.setCapability("ignoreProtectedModeSettings", true);
        capabilities.setCapability("initialBrowserUrl", "https://stackoverflow.com/");
        ieDriver = new InternetExplorerDriver(capabilities);
        Shutterbug.shootPage(ieDriver, ScrollStrategy.WHOLE_PAGE,500,true).save("screenshots");
```

and got this screenshot with IE driver version 4.0

![2019_10_03_15_32_23_329](https://user-images.githubusercontent.com/16775850/66136585-9ddf9500-e5f3-11e9-9bfe-670c3ee35c59.png)

**Comment by Vitalthorbi** [comment]
@glib-briia , I'm using 3.14.0 found [here](https://www.seleniumhq.org/download/)

**Comment by Vitalthorbi** [comment]
I couldn't find the standalone .exe for version 4.0, could you share where you grabbed that?

`System.setProperty("webdriver.ie.driver", System.getProperty("user.dir") + "/src/main/resources/IEDriver.exe");`

**Comment by glib-briia** [comment]
Sorry, I meant 3.4.0. You can download it here https://selenium-release.storage.googleapis.com/3.4/IEDriverServer_Win32_3.4.0.zip

**Comment by Vitalthorbi** [comment]
Just tried it with 3.4.0 and the gaps issues are gone, so great progress. But it's still cutting off on the right side...

**Comment by Vitalthorbi** [comment]
![2019_10_03_12_09_15_500](https://user-images.githubusercontent.com/52708142/66148599-e76db700-e5d6-11e9-9452-02f86298a751.png)

**Comment by Vitalthorbi** [comment]
@glib-briia Do you know why it might be cutting off on the side like that? Is there is a default Shutterbug setting affecting the screensize?

**Comment by glib-briia** [comment]
IE is going out of support
