### ISSUE TITLE
Capture screenshot not proper in mac safari browser

### ISSUE THREAD

**Issue by jnlodhiya** [assertthat/selenium-shutterbug#63]
WebDriver driver = new SafariDriver();
		driver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);
		driver.manage().window().maximize();

		driver.get("https://www.amazon.in/");
	   
		
		Shutterbug.shootPage(driver, ScrollStrategy.WHOLE_PAGE).save("/Users/abc/Documents/web.png");
		
		driver.quit();
![2019_11_06_14_17_43_968](https://user-images.githubusercontent.com/57446330/68303174-530cdd80-00c9-11ea-8bba-442f57432a34.png)

The vertical site has been cut.

**Comment by glib-briia** [comment]
Fixed with setting devidcePixelRatio
