### ISSUE TITLE
In whole-page screenshots with Firefox only the upper part of the page is captured

### ISSUE THREAD

**Issue by kema91** [assertthat/selenium-shutterbug#64]
Hi, 

I'm dealing with the problem that when taking a whole page screenshot, only the upper part of the viewport is taken. 

![2019_11_07_14_13_58_326](https://user-images.githubusercontent.com/42932182/68392654-7f2c6b00-016a-11ea-89ed-524627578d14.png)

### Used versions:

Firefox version 70.0.1 (64-Bit)
geckodriver-v0.26.0-macos
Java OpenJDK 11
macOS Catalina Version 10.15.1
selenium-java version 3.141.59
selenium-shutterbug version 0.9.3

### Here's a snippet of the relevant code:

```java
final FirefoxOptions opts = new FirefoxOptions();
opts.addArguments( "--headless", "--window-size=1200,800" );
driver = new FirefoxDriver( opts );

driver.get( "https://stackoverflow.com" );
Shutterbug.shootPage( driver, ScrollStrategy.WHOLE_PAGE, 500, true ).save( "/Users/abc/Downloads/whole_page" );

driver.quit();
```

Thanks in advance.

**Comment by glib-briia** [comment]
Should be fixed with new Capture strategies in v1.0
