### ISSUE TITLE
Add timeout for chrome full page screenshot

### ISSUE THREAD

**Issue by SergeyPirogov** [assertthat/selenium-shutterbug#68]
I see that it scrolls the page and then back to top and take a screenshot. There should be a possibility to set a timeout between these operations because sometimes need to wait while page will be fully rendered and all effects stop after scroll 

![image](https://user-images.githubusercontent.com/4622856/76945012-9f371c80-690a-11ea-8f50-030109b1f6a3.png)

**Comment by glib-briia** [comment]
Hi @SergeyPirogov ,

Thank you for your suggestion. There is a timeout after scroll here https://github.com/assertthat/selenium-shutterbug/blob/c20770b8260b3c85aa6df065d88ec56d653fd9b5/src/main/java/com/assertthat/selenium_shutterbug/utils/web/Browser.java#L186

Can be used like so ```Shutterbug.shootPage(driver, ScrollStrategy.WHOLE_PAGE , scrollTimeout)```

If that wont work we can then add a separate wait after all scrolling finishes.

**Comment by SergeyPirogov** [comment]
The problem is that sometimes there should be timeout between SetDeviceMetrics and captureScreenshot actions

**Comment by glib-briia** [comment]
Alright, np,  I'll add it in

**Comment by glib-briia** [comment]
Snapshot with this change is available here https://oss.sonatype.org/content/repositories/snapshots/com/assertthat/selenium-shutterbug/0.9.4-SNAPSHOT/

**Comment by SergeyPirogov** [comment]
There even might be a better solution for these timeouts. Just to replace both of the with Java callable Callable<boolean>. So users will be able to wait for some events using external tools (ex Selenium, Selenide)

**Comment by glib-briia** [comment]
Thank you for suggestion. Added conditional waiting after scroll and before taking screenshot https://github.com/assertthat/selenium-shutterbug/commit/d4ddbe8bbcfd1c28c8f8ea88062e2f0f2379288b

So it can be used like 
```
        Shutterbug.wait(visibilityOfElementLocated(By.id("someId")), 5)
                .shootPage(driver, ScrollStrategy.WHOLE_PAGE).save();
```

The change will be available in next minor version update
