### ISSUE TITLE
"Images dimensions mismatch" error in full page screenshot comparison

### ISSUE THREAD

**Issue by jpratt2** [assertthat/selenium-shutterbug#70]
I would like to be able to use the equalsWithDiff function when using a full-page screenshot.
Currently I git this error:
"Images dimensions mismatch: image1 - 1548x3284; image2 - 1548x3291"

The difference is 7 pixels in height. I am using Chrome.

My code:
```
 BufferedImage expectedImage = null;
        try {
            expectedImage = ImageIO.read(new File("C:\\2020_06_12_13_25_31_832.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }
Shutterbug.shootPage(driver,ScrollStrategy.WHOLE_PAGE).equalsWithDiff(expectedImage,"screenshots2");
```

**Comment by glib-briia** [comment]
Hi @jpratt2 ,

Were screenshots taken on different systems/PCs? That may happen if you taking baseline screenshot on windows and run your comparison on e.g. headless linux

**Comment by jpratt2** [comment]
I can no longer duplicate this issue. Please disregard this.

**Comment by jpratt2** [comment]
Actually, I think I fixed it by adding a 3-second delay for the page to finish loading

**Comment by jpratt2** [comment]
Glib, I would like to re-open this.
Which is better, to still create a diff image with the difference in height highlighted in red, or to throw an error?

I am still getting this error from time to time, and I am investigating the cause. Meanwhile, wouldn't it be best to still make a diffimage?

**Comment by jpratt2** [comment]
And for the record, I found the culprit: some pages had an a/b test. And some pages had slight variances due to IP localization; it mattered if I connected via VPN.

**Comment by Chankami** [comment]
Hi 
I'm also facing the same issue @jpratt2  how you resolve this? Im using the same machine to generate the baseline and actual screenshot.

**Comment by jpratt2** [comment]
@Chankami  -- actually I didn't solve it.

Glib, I am getting this error on pages that are not affected by the reasons I stated earlier. Could it be a RAM limitation? I am using my machine simultaneously, and I don't know what else it could be.
I can't duplicate it predictably, but in this example, we see that image 1 (the image diff) is slightly longer than the original, 2215px vs 2192px.
  _01_assertScreenshots(B_imageDiffTest): Images dimensions mismatch: image1 - 1898x2215; image2 - 1898x2192

**Comment by glib-briia** [comment]
Hi @jpratt2 , at the moment its pixel by pixel comparison only. I'll have a look at possible reasons why the size differs.

**Comment by nanomiju** [comment]
Hi
Has anyone found a solution for the size mismatch? I'm getting the same error message when capturing full-sized screenshots (both screenshots were taken on the same machine).

**Comment by Menikonda** [comment]
Can some one please help me to blur certain portion of text on UI.
Per example <td>First Name</td> I would need to blur only "Name"

Any help please.

**Comment by jpratt2** [comment]
In case it helps, here are some details, as I am seeing this again. I don't think it is a RAM issue, but it may be the same issue as https://github.com/assertthat/selenium-shutterbug/issues/89
I will attach the full screenshots, the test URL, the code used, and the error.
Error:
  _01_intro(basicTests.A_basicTest): Images dimensions mismatch: image1 - 1295x7740; image2 - 1295x7726
URL:
`        driver.get("http://acrobat.adobe.com/us/en/?mboxDisable=1");
`
Shutterbug code:
`        shootPage(driver,  Capture.FULL).withName(fileName).save(folderPath);
`
It seems that sometimes there are some missing pixels at the bottom which causes mismatch error as mentioned above.
7740 size:
![acrobat adobe com-us-en--mboxDisable=1](https://user-images.githubusercontent.com/18728354/113081353-607aaa00-918d-11eb-9fc7-ef06a108af1d.png)
7726 size:
![acrobat adobe com-us-en-2](https://user-images.githubusercontent.com/18728354/113081433-82742c80-918d-11eb-9eea-cf8f7b73b96f.png)
A comparison at the bottom of each image may be the difference:

![a difference of about 10 px](https://user-images.githubusercontent.com/18728354/113081631-e7c81d80-918d-11eb-8ba0-2abb3e933291.png)

One idea is to allow the image diff to continue if the difference is only about 15 px, but of course, it would be better if there were no difference.
These screenshots were taken in Chrome 89 on Windows 10 on a machine with 16 GB Ram. I don't think it is limited in resources.

**Comment by jpratt2** [comment]
and now I see there is a difference of a scroll bar

**Comment by jpratt2** [comment]
I think this is the heart of the issue: the method to compare a screenshot image should have a ms parameter for a delay for the page to fully load.
Or provide an option to compare 2 existent images.
