### ISSUE TITLE
Any option to get image file name with timestamp

### ISSUE THREAD

**Issue by vignesh6300** [assertthat/selenium-shutterbug#74]
I know it is possible to get file name either time stamp or custom name. I want to know if it is possible to get both time stamp and custom name for image file name.
Ex: Github_2020_06_19_21_17_45_761.png

**Comment by glib-briia** [comment]
Hi @vignesh6300 ,

Yes, sure you can construct it like so
```
String fileName = "Github_" +  new SimpleDateFormat("yyyy_MM_dd_HH_mm_ss_SSS").format(new Date());
 Shutterbug.shootPage(driver).withName(fileName).save();
```

**Comment by vignesh6300** [comment]
It works as expected. Thanks a lot @glib-briia !!
