### ISSUE TITLE
suggestion: overwrite old files in equalsWithDiff

### ISSUE THREAD

**Issue by jpratt2** [assertthat/selenium-shutterbug#76]
I suggest that the .equalsWithDiff method should overwrite old images with the same name, similar to what happens in the .withName method.

**Comment by jpratt2** [comment]
Code example:
`Shutterbug.shootPage(driver).equalsWithDiff(expectedImage,"observed\\diffImage6")`
If there is already an image named diffImage6, overwrite it with the latest diff

**Comment by glib-briia** [comment]
Hi @jpratt2 ,
It's overriding the image already (using same mechanism as in withName). Could you please elaborate what is not working in your example?

**Comment by jpratt2** [comment]
I agree, this is already working. I was mistaken. Thank you.
