### ISSUE TITLE
Tried with horizontal scrolling with WHOLE_PAGE strategy but image at end of page is not capturing properly 

### ISSUE THREAD

**Issue by achatap** [assertthat/selenium-shutterbug#78]
I want to take a full-page screenshot of "https://www.album.alexflueras.ro/index.php" this URL, but when I try to take a screenshot of the whole page, then image at the end part of the page is not captured properly. 

Please check the image here: (https://ibb.co/k13T2v9 )(size of image is 24.6MB, that's why I am not able to attach here)

Code: 

        driver = new FirefoxDriver();

        driver.get("https://www.album.alexflueras.ro/index.php");
        driver.manage().window().maximize();

        Shutterbug.shootPage(driver, ScrollStrategy.WHOLE_PAGE, 1000, true).save("E:\\NewElementScreenshot.jpeg");

        driver.close();

Can anyone please help me?

**Comment by glib-briia** [comment]
Hi @achatap ,

I've added back WHOLE_PAGE_SCROLL_AND_STITCH strategy which should give you desired result.

You can try 

```
    driver = new FirefoxDriver();

    driver.get("https://www.album.alexflueras.ro/index.php");
    driver.manage().window().maximize();

    Shutterbug.shootPage(driver, ScrollStrategy.WHOLE_PAGE_SCROLL_AND_STITCH, 1000, true).save("E:\\NewElementScreenshot.jpeg");

    driver.close();
```

Available in version 0.9.5

**Comment by achatap** [comment]
@glib-briia , that's really great work. It works absolutely fine. But I have tried with "http://www.mike-tucker.com/10/#/" with this URL but now I am getting error as "Exception in thread "main" java.lang.IllegalArgumentException: Width (1920) and height (0) cannot be <= 0". Could you please help me to fix this.

**Comment by glib-briia** [comment]
@achatap, it works fine in Chrome, I'll have a look what's the issue in FF, looks like it's something to do how it handles <canvas> element.

**Comment by achatap** [comment]
@glib-briia , for IE tried with 
case "ie":
			System.setProperty("webdriver.ie.driver","C:\\Webdrivers\\IEDriverServer.exe");
			driver = new InternetExplorerDriver();
	    	break;

but getting error as: Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unexpected error launching Internet Explorer. Browser zoom level was set to 125%. It should be set to 100%

Do I need to change anything in the above code?

**Comment by glib-briia** [comment]
@achatap 

Try this solution. This is not shutterbug issue but IE driver issue.

```
DesiredCapabilities caps = DesiredCapabilities.internetExplorer();
caps.setCapability("ignoreZoomSetting", true);
driver = new InternetExplorerDriver(caps);
```

more here https://groups.google.com/forum/?fromgroups=#!topic/webdriver/pZuj9uU1Evc

**Comment by achatap** [comment]
@glib-briia Thanks for the solution, but when I checked with the IE screenshot is not capture properly. Please check the attachment.
![2020_07_29_13_25_05_209](https://user-images.githubusercontent.com/18513319/88773061-48d2c800-d19f-11ea-9940-7ccd4886d857.png) Site URL: http://www.weshootbottles.com/

Can you please help?

**Comment by glib-briia** [comment]
IE is going out of support
