### ISSUE TITLE
How to use `WHOLE_PAGE` with scrollable `div`?

### ISSUE THREAD

**Issue by roboaks** [assertthat/selenium-shutterbug#79]
We are using Shutterbug with a system that uses a popular UI framework where the bulk of the screen is within a scrollable `div` (styled with `overflow-y: scroll`). We primarily using Chrome but need to support Firefox as well. The problem appears to be centered within Shutterbug's
`takeScreenshotEntirePageUsingChromeCommand` method and, in particular, within this code:
```
 int verticalIterations = (int) Math.ceil(((double) this.getDocHeight()) / this.getViewportHeight());
        for (int j = 0; j < verticalIterations; j++) {
            this.scrollTo(0, j * this.getViewportHeight());
            wait(scrollTimeout);
        }
```

Since this method operates on the browser window itself, not any particular scrollable element, `verticalIterations` is calculated improperly and `this.scrollTo` simply scrolls the window to take the whole page screenshot.

Is there a solution?

**Comment by roboaks** [comment]
It is worth noting that, in some respects, this relates to issue #30, which was posted by my colleague a while back. In both cases, the issue occurs where the scroll bar is owned by a child element, and not `window`. The DOM supports `scrollTo` for any element, so it's certainly an issue that should be solvable. 

In terms of the fluent methods that are already defined, it seems to me that we want to be able to write thing like:
```
Shutterbug.shootElement(element, driver, ScrollStrategy.WHOLE_PAGE).save();
```

**Comment by glib-briia** [comment]
Implements in v1.0 e.g. 

```
Shutterbug.shootElement(driver,element, Capture.FULL_SCROLL).save();
```
