### ISSUE TITLE
Ability to remove part of image.

### ISSUE THREAD

**Issue by woj1993** [assertthat/selenium-shutterbug#84]
It's my second enchantment request. I would want to propose something new. On sites we can take images using Shutterbug and compare. But there is a problem with part of site that changes (example scrolling images) we will need to give huge margin of error or don't use it for such sites. There is also ability to use it for smaller parts (elements) but it doesn't allow us to check if everything is in place, we can only check elements look.

I would want to propose something like blur. it's removing element of site from image. We can for example make it transparent so we don't compare it.

Please comment this idea. Tell me if you liked it or not and why.

**Comment by glib-briia** [comment]
Hi @woj1993 ,

Thank you for suggestion. I've added the following methods to cut out part(s) of the image:

```
  Shutterbug.shootPage(driver).cutOut(element).save(); //can pass single element to cut out or an array of elements
  Shutterbug.shootPage(driver).cutOut(offsetX, offsetY, element).save(); //can pass single element to cut out or an array of elements. Offset is used for cutting out larger portion of the image around the element. E.g if an element has a shadow effect.
```

The change will be available in next version v.1.3

Thanks,
Glib
