### ISSUE TITLE
Full page screenshots occasionally missing some pixels at the bottom

### ISSUE THREAD

**Issue by johannes-namics** [assertthat/selenium-shutterbug#89]
Hi,

I use Shutterbug in Chrome on Windows 10.
When I take a full page screenshot of a page that's a bit longer (~6000+ pixels), occasionally I get a screenshot that's not comparable due to mismatch of dimensions. Then, when I look at it I notice that the screenshot is a little shorter in height than the baseline shot. About 40 - 60 pixels get cut off at the bottom.

I started using Shuttebug at v.0.9.3 and I've always had this issue. Recently I updated to 1.3 and changed the capture type to `Capture.FULL` (using Chrome dev tools) hoping it would solve this issue. Unfortunately it hasn't.

Any idea what could be the problem?

Any support will be very much appreciated. :-)

Cheers,
Johannes

**Comment by glib-briia** [comment]
Hi @johannes-namics ,

Could you please provide example screenshots and details of your execution environment (user agent, browser, driver version, os)?

Could be related to scrollbars calculation issue in different browsers.

Cheers,
Glib

**Comment by johannes-namics** [comment]
Hi @glib-briia ,

the user agent is `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36`
Chrome version is `88.0.4324.104`
ChromeDriver version is `88.0.4324.96`
Windows 10 Pro version is `10.0.19042 Build 19042`

I cannot provide the full screenshot for data privacy reasons. But I've taken a snapshot of the bottom of the actual webpage (left) next to the bottom of the screenshot I've taken using Shutterbug (right), so you can get an idea of how much is being cut off:
![screenshot-cut-bottom](https://user-images.githubusercontent.com/30800542/111340288-c983fd00-8678-11eb-91f2-63b8e77b33be.PNG)
