### ISSUE TITLE
[add Feature] about rename file in withname(variable)

### ISSUE THREAD

**Issue by ridhoadilla** [assertthat/selenium-shutterbug#94]
hey all , 
it is my first time request / i just use selenium shutterbug .
if I add example 
`String titlevar = driver.getTitle();
 Shutterbug.shootPage(driver).withName(titlevar).save("D:\\");
`

i got file output  screenshot but with zero byte size file  even the name file is as same as title get from variable .

please help ,
Regards

**Comment by glibas** [comment]
Hi @ridhoadilla ,
Apologies for taking long to get back. Have you got a reproducible example? Is this still an issue?

**Comment by glibas** [comment]
Closing as outdated. Feel free to reopen is still an issue
