### ISSUE TITLE
Screenshots with getBytes() don't have title when it is set

### ISSUE THREAD

**Issue by anna-shchurok** [assertthat/selenium-shutterbug#97]
Code like 
`Shutterbug.shootPage(driver, Capture.FULL).withTitle("Title goes here").getBytes()`
doesn't return screenshot with title added
although code like 
`Shutterbug.shootPage(driver, Capture.FULL).withTitle("Title goes here").save()`
saves screenshot with title added

**Comment by anna-shchurok** [comment]
Hi me,

fixed issue in #98,

error appeared with new version of Shutterbug
Could not initialize class sun.awt.X11GraphicsEnvironment
setting property `-Djava.awt.headless=true` omits the problem

**Comment by glib-briia** [comment]
Hi @anna-shchurok  thank you very much for contribution. 

Shall we set java.awt.headless=true programmatically while initialiszing Shutterbug?

**Comment by anna-shchurok** [comment]
@glib-briia 
I am for option when it is added not optionally. I mean in what cases people would care if AWT headless or not and also writing `headless` each time probably would be excessive.
or you don't think so?

**Comment by glib-briia** [comment]
@anna-shchurok agreed. Lets have it permanently set to true and provide option of disabling by Shutterbug.headless(false)
